<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<title>Libros</title>

</head>

<body>

<h2><?=$titulo?></h2>

<ul class="list-group">
    
    <?php foreach($libros as $libro): ?>
        <li class="list-group-item">Titulo: <?= $libro->titulo ?></li>
        <li class="list-group-item">Autor: <?= $libro->autor ?></li>
        <li class="list-group-item">Fecha de Publicacion: <?= $libro->fecha_publicacion ?></li>
        <li class="list-group-item">Editorial: <?= $libro->editorial ?></li>
        <li class="list-group-item">Genero: <?= $libro->genero ?></li>
        <li class="list-group-item">Cantidad de Copias: <?= $libro->cantidad_copias ?></li>
    <?php endforeach; ?>

</ul>

</body>
</html>