<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<title>Prestamos</title>

</head>

<body>

<h2><?=$titulo?></h2>

<ul class="list-group">
    
    <?php foreach($prestamos as $prestamo): ?>
        <li class="list-group-item">Id de Usuario: <?= $prestamo->id_usuario ?></li>
        <li class="list-group-item">Id de Libro: <?= $prestamo->id_libro ?></li>
        <li class="list-group-item">Fecha de Prestamo: <?= $prestamo->fecha_prestamo ?></li>
        <li class="list-group-item">Fecha de Devolucion: <?= $prestamo->fecha_devolucion ?></li>
    <?php endforeach; ?>

</ul>

</body>
</html>