<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<title>Usuarios</title>

</head>

<body>

<h2><?=$titulo?></h2>

<ul class="list-group">
    
    <?php foreach($usuarios as $usuario): ?>
        <li class="list-group-item">Nombre: <?= $usuario->nombre ?></li>
        <li class="list-group-item">Apellido: <?= $usuario->apellido ?></li>
        <li class="list-group-item">Direccion: <?= $usuario->direccion ?></li>
        <li class="list-group-item">Mail: <?= $usuario->mail ?></li>
        <li class="list-group-item">Telefono: <?= $usuario->telefono ?></li>
        <li class="list-group-item">Fecha de Registro: <?= $usuario->fecha_registro ?></li>
    <?php endforeach; ?>

</ul>



</body>
</html>