<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<base href='.URL_CATEGORIAS.' >
<title>Categorias</title>

</head>

<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="log-out">Log Out</a>
      </div>
    </div>
  </div>
</nav>

<h2><?=$tituloPrestamos?></h2>

<ul class="list-group">

    <?php foreach($prestamos as $prestamo): ?>
        <li class="list-group-item">Prestamo: <?= $prestamo->id_prestamo ?>
        <a href="descripcion-prestamo/<?php echo htmlspecialchars($prestamo->id_prestamo); ?>">Descripción</a>
        <a href="eliminar-prestamo/<?php echo htmlspecialchars($prestamo->id_prestamo); ?>">Eliminar</a>
        <a href="modificar-prestamo">Modificar</a>
        </li>
    <?php endforeach; ?>

</ul>

<h2>Agregar Prestamo</h2>

<form action="insertar-prestamo" method="POST">
  <div class="form-group">
    <label for="id-usuario">ID Usuario</label>
    <input type="number" class="form-control" name="id-usuario" placeholder="ID Usuario" required>
  </div>
  <div class="form-group">
    <label for="id-libro">ID Libro</label>
    <input type="number" class="form-control" name="id-libro" placeholder="ID Libro" required>
  </div>
  <div class="form-group">
    <label for="fecha-prestamo">Fecha Prestamo</label>
    <input type="date" class="form-control" name="fecha-prestamo" placeholder="Fecha Prestamo" required>
  </div>
  <div class="form-group">
    <label for="fecha-devolucion">Fecha Devolucion</label>
    <input type="date" class="form-control" name="fecha-devolucion" placeholder="Fecha Devolucion" required>
  </div>
  <button type="submit" class="btn btn-primary">Agregar</button>
</form>

<h2><?=$tituloUsuarios?></h2>

<ul class="list-group">

    <?php foreach($usuarios as $usuario): ?>
        <li class="list-group-item">Usuario: <?= $usuario->id_usuario ?>
        <a href="descripcion-usuario/<?php echo htmlspecialchars($usuario->id_usuario); ?>">Descripción</a>
        <a href="eliminar-usuario/<?php echo htmlspecialchars($usuario->id_usuario); ?>">Eliminar</a>
        <a href="modificar-usuario">Modificar</a>
        </li>
    <?php endforeach; ?>

</ul>

<h2>Agregar Usuario</h2>

<form action="insertar-usuario" method="POST">
  <div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control" name="nombre" placeholder="Nombre" required>
  </div>
  <div class="form-group">
    <label for="apellido">Apellido</label>
    <input type="text" class="form-control" name="apellido" placeholder="apellido" required>
  </div>
  <div class="form-group">
    <label for="direccion">Direccion</label>
    <input type="text" class="form-control" name="direccion" placeholder="Direccion" required>
  </div>
  <div class="form-group">
    <label for="mail">Email</label>
    <input type="text" class="form-control" name="mail" placeholder="Email" required>
  </div>
  <div class="form-group">
    <label for="telefono">Telefono</label>
    <input type="text" class="form-control" name="telefono" placeholder="Telefono" required>
  </div>
  <div class="form-group">
    <label for="fecha-registro">Fecha Registro</label>
    <input type="date" class="form-control" name="fecha-registro" placeholder="Fecha Registro" required>
  </div>
  <button type="submit" class="btn btn-primary">Agregar</button>
</form>

<h2><?=$tituloLibros?></h2>

<ul class="list-group">

    <?php foreach($libros as $libro): ?>
        <li class="list-group-item">Libro: <?= $libro->id_libro ?>
        <a href="descripcion-libro/<?php echo htmlspecialchars($libro->id_libro); ?>">Descripción</a>
        <a href="eliminar-libro/<?php echo htmlspecialchars($libro->id_libro); ?>">Eliminar</a>
        <a href="modificar-libro">Modificar</a>
        </li>
    <?php endforeach; ?>

</ul>

<h2>Agregar Libros</h2>

<form action="insertar-libro" method="POST">
  <div class="form-group">
    <label for="titulo">Titulo</label>
    <input type="text" class="form-control" name="titulo" placeholder="Titulo" required>
  </div>
  <div class="form-group">
    <label for="autor">Autor</label>
    <input type="text" class="form-control" name="autor" placeholder="Autor" required>
  </div>
  <div class="form-group">
    <label for="fecha-publicacion">Fecha Publicacion</label>
    <input type="date" class="form-control" name="fecha-publicacion" placeholder="Fecha Publicacion" required>
  </div>
  <div class="form-group">
    <label for="editorial">Editorial</label>
    <input type="text" class="form-control" name="editorial" placeholder="Editorial" required>
  </div>
  <div class="form-group">
    <label for="genero">Genero</label>
    <input type="text" class="form-control" name="genero" placeholder="Genero" required>
  </div>
  <div class="form-group">
    <label for="cantidad-copias">Cantidad Copias</label>
    <input type="number" class="form-control" name="cantidad-copias" placeholder="Cantidad Copias" required>
  </div>
  <button type="submit" class="btn btn-primary">Agregar</button>
</form>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>