<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<base href='.BASE_URL.' >
<title>Prestamos</title>

</head>

<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="prestamos">Prestamos</a>
        <a class="nav-link" href="usuarios">Usuarios</a>
        <a class="nav-link" href="libros">Libros</a>
        <a class="nav-link" href="log-in">Log In</a>
      </div>
    </div>
  </div>
</nav>


<h2><?=$titulo?></h2>

<ul class="list-group">

    <?php foreach($prestamos as $prestamo): ?>
        <li class="list-group-item">Prestamo: <?= $prestamo->id_prestamo ?>
        <a href="descripcion-prestamo/<?php echo htmlspecialchars($prestamo->id_prestamo); ?>">Descripción</a>
        </li>
    <?php endforeach; ?>

</ul>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>