<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<base href='.URL_LOGIN.' >
<title>Log In</title>

</head>

<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="prestamos">Prestamos</a>
        <a class="nav-link" href="usuarios">Usuarios</a>
        <a class="nav-link" href="libros">Libros</a>
      </div>
    </div>
  </div>
</nav>

<h2><?=$titulo?></h2>

<form action="iniciarSesion" method="post">
  <div class="form-group">
    <label for="email">Email</label>
    <input type="text" class="form-control" name="user" placeholder="Enter email" required>
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" name="pass" placeholder="Password" required>
  </div>
  <button type="submit" class="btn btn-primary">Log In</button>
</form>

<?php 
    session_start();
    if (isset($_SESSION['error'])): ?>
    <div>
        <?= $_SESSION['error'] ?>
    </div>
    <?php unset($_SESSION['error']);?>
<?php endif; ?>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>