<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<title>Libros</title>

</head>

<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="categorias">Categorias</a>
        <a class="nav-link" href="log-out">Log Out</a>  
      </div>
    </div>
  </div>
</nav>



<h1><?=$titulo?></h1>

<form action="enviarM-libro" method="POST">
  <div class="form-group">
    <label for="id-libro">ID Libro</label>
    <input type="number" class="form-control" name="id-libro" placeholder="ID Libro" required>
  </div>
  <div class="form-group">
    <label for="titulo">Titulo</label>
    <input type="text" class="form-control" name="titulo" placeholder="Titulo" required>
  </div>
  <div class="form-group">
    <label for="autor">Autor</label>
    <input type="text" class="form-control" name="autor" placeholder="Autor" required>
  </div>
  <div class="form-group">
    <label for="fecha-publicacion">Fecha Publicacion</label>
    <input type="date" class="form-control" name="fecha-publicacion" placeholder="Fecha Publicacion" required>
  </div>
  <div class="form-group">
    <label for="editorial">Editorial</label>
    <input type="text" class="form-control" name="editorial" placeholder="Editorial" required>
  </div>
  <div class="form-group">
    <label for="genero">Genero</label>
    <input type="text" class="form-control" name="genero" placeholder="Genero" required>
  </div>
  <div class="form-group">
    <label for="cantidad-copias">Cantidad Copias</label>
    <input type="number" class="form-control" name="cantidad-copias" placeholder="Cantidad Copias" required>
  </div>
  <button type="submit" class="btn btn-primary">Agregar</button>
</form>
    

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>