<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<title>Prestamos</title>

</head>

<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="categorias">Categorias</a>
        <a class="nav-link" href="log-out">Log Out</a>  
      </div>
    </div>
  </div>
</nav>

<h1><?=$titulo?></h1>

<form action="enviarM-prestamo" method="POST">
  <div class="form-group">
    <label for="id-prestamo">ID Prestamo</label>
    <input type="number" class="form-control" name="id-prestamo" placeholder="ID Prestamo" required>
  </div>
  <div class="form-group">
    <label for="id-usuario">ID Usuario</label>
    <input type="number" class="form-control" name="id-usuario" placeholder="ID Usuario" required>
  </div>
  <div class="form-group">
    <label for="id-libro">ID Libro</label>
    <input type="number" class="form-control" name="id-libro" placeholder="ID Libro" required>
  </div>
  <div class="form-group">
    <label for="fecha-prestamo">Fecha Prestamo</label>
    <input type="date" class="form-control" name="fecha-prestamo" placeholder="Fecha Prestamo" required>
  </div>
  <div class="form-group">
    <label for="fecha-devolucion">Fecha Devolucion</label>
    <input type="date" class="form-control" name="fecha-devolucion" placeholder="Fecha Devolucion" required>
  </div>
  <button type="submit" class="btn btn-primary">Agregar</button>
</form>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>