<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<title>Usuarios</title>

</head>

<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="categorias">Categorias</a>
        <a class="nav-link" href="log-out">Log Out</a>  
      </div>
    </div>
  </div>
</nav>

<h1><?=$titulo?></h1>
<form action="enviarM-usuario" method="POST">
  <div class="form-group">
    <label for="id-usuario">ID Usuario</label>
    <input type="number" class="form-control" name="id-usuario" placeholder="ID Usuario" required>
  </div>
  <div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control" name="nombre" placeholder="Nombre" required>
  </div>
  <div class="form-group">
    <label for="apellido">Apellido</label>
    <input type="text" class="form-control" name="apellido" placeholder="apellido" required>
  </div>
  <div class="form-group">
    <label for="direccion">Direccion</label>
    <input type="text" class="form-control" name="direccion" placeholder="Direccion" required>
  </div>
  <div class="form-group">
    <label for="mail">Email</label>
    <input type="text" class="form-control" name="mail" placeholder="Email" required>
  </div>
  <div class="form-group">
    <label for="telefono">Telefono</label>
    <input type="text" class="form-control" name="telefono" placeholder="Telefono" required>
  </div>
  <div class="form-group">
    <label for="fecha-registro">Fecha Registro</label>
    <input type="date" class="form-control" name="fecha-registro" placeholder="Fecha Registro" required>
  </div>
  <button type="submit" class="btn btn-primary">Agregar</button>
</form>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>